name:                simple-cairo
version:             0.1.0.0
github:              "YoshikuniJujo/simple-cairo"
license:             BSD3
author:              "Yoshikuni Jujo"
maintainer:          "PAF01143@nifty.ne.jp"
copyright:           "Yoshikuni Jujo"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/YoshikuniJujo/simple-cairo#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- stm
- primitive
- bytestring
- text
- vector
- exception-hierarchy
- c-struct
- union-angle
- cairo-image

library:
  source-dirs: src
  pkg-config-dependencies: cairo

tests:
  exception-test:
    main:                exception.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-cairo
  cairo-image-test:
    main:                cairo-image-test.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-cairo
  test-rotate:
    main:                test-rotate.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simple-cairo

data-dir: data

data-files:
- HaskellLogo.png
